2024-09-06 03:22:16 jdbc[3]: exception
com.craftaro.third_party.org.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 42S02 not found); SQL statement:
SELECT 1 FROM ultimatekits_migrations [42102-200]
2024-09-06 03:48:53 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 04:09:25 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 04:09:25 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 04:13:03 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 04:21:08 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 05:27:11 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 05:31:06 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 05:51:46 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 05:51:47 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 06:07:02 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2024-09-06 06:10:58 database: flush
com.craftaro.third_party.org.h2.message.DbException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.get(DbException.java:194)
	at com.craftaro.third_party.org.h2.message.DbException.convert(DbException.java:347)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at com.craftaro.third_party.org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at com.craftaro.third_party.org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at com.craftaro.third_party.org.h2.engine.Database.getPageStore(Database.java:2659)
	at com.craftaro.third_party.org.h2.engine.Database.open(Database.java:675)
	at com.craftaro.third_party.org.h2.engine.Database.openDatabase(Database.java:307)
	at com.craftaro.third_party.org.h2.engine.Database.<init>(Database.java:301)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:74)
	at com.craftaro.third_party.org.h2.engine.Engine.openSession(Engine.java:192)
	at com.craftaro.third_party.org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:166)
	at com.craftaro.third_party.org.h2.engine.Engine.createSession(Engine.java:29)
	at com.craftaro.third_party.org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at com.craftaro.third_party.org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at com.craftaro.third_party.org.h2.Driver.connect(Driver.java:69)
	at com.craftaro.third_party.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.craftaro.third_party.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.craftaro.third_party.org.h2.jdbc.JdbcSQLNonTransientException: (Message HY000 not found) [50000-200]
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at com.craftaro.third_party.org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/workspaces/RageSMP/server/plugins/UltimateKits/ultimatekits.mv.db [1.4.200/7]
	at com.craftaro.third_party.org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:166)
	at com.craftaro.third_party.org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1321)
	at com.craftaro.third_party.org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at com.craftaro.third_party.org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
